providers = ["python"]

[phases.setup]
aptPkgs = [
    "libasound2",
    "libatk-bridge2.0-0",
    "libatk1.0-0",
    "libcairo2",
    "libcups2",
    "libdrm2",
    "libexpat1",
    "libgbm1",
    "libglib2.0-0",
    "libnss3",
    "libpango-1.0-0",
    "libx11-xcb1",
    "libxcb-dri3-0",
    "libxcomposite1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxkbcommon0",
    "libxrandr2",
    "libxshmfence1"
]

[phases.build]
cmds = [
    "python -m pip install -r requirements.txt",
    "patchright install chromium"
]
